# Generated by Django 5.0.6 on 2025-07-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.URLField(blank=True, help_text='URL to company logo', null=True)),
                ('price_band_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_band_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='Issue size in Crores', max_digits=20)),
                ('issue_type', models.CharField(help_text='e.g., Book Built, Fixed Price', max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('listed', 'Listed')], default='upcoming', max_length=20)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final IPO price', max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rhp_document', models.URLField(blank=True, help_text='URL to Red Herring Prospectus', null=True)),
                ('drhp_document', models.URLField(blank=True, help_text='URL to Draft Red Herring Prospectus', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-open_date'],
            },
        ),
    ]
